name: Build and Deploy

on:
  push:
    branches:
      - main
      - dev
      - stg

  workflow_dispatch:
    inputs:
      force:
        description: 'Force exec'
        type: boolean
        required: true

jobs:
  Detect:
    runs-on: ubuntu-latest
    outputs:
      app: ${{ steps.detect.outputs.app }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Detect Change
        id: detect
        run: |
          APP="Serilog.Sinks.Queuing.Worker"
          
          CHANGE_FILES=`git diff --no-commit-id --name-only HEAD^`
          
          CHANGED=`echo "$CHANGE_FILES" | grep -Em 1 "${APP}|${APP_CORE}" || true`
          if [ -z "$CHANGED" ] && [ "${{ inputs.force }}" != true ]; then
            echo "No changes in ${APP}"
            APP=""
          fi
          
          echo "app=${APP}" >> $GITHUB_OUTPUT
  Build:
    name: "Build ${{ needs.Detect.outputs.app }}"
    needs: Detect
    if: needs.Detect.outputs.app != ''
    runs-on: ubuntu-latest
    env:
      app: ${{ needs.Detect.outputs.app }}
    outputs:
      app: ${{ steps.envs.outputs.app }}
      branch: ${{ steps.envs.outputs.branch }}
      image: ${{ steps.envs.outputs.image }}
      tag: ${{ steps.envs.outputs.tag }}
      tag-hash: ${{ steps.envs.outputs.tag-hash }}
      tag-latest: ${{ steps.envs.outputs.tag-latest }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - id: envs
        uses: netcorext/dotnet-version-action@dev
        with:
          app: ${{ env.app }}
          image-prefix: ${{ secrets.IMAGE_PREFIX }}
      - uses: netcorext/dotnet-dockerfile-action@dev
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build Image & Push
        uses: netcorext/buildx-image-action@dev
        with:
          image: ${{ steps.envs.outputs.image-fullName }}
          tag: ${{ steps.envs.outputs.tag }}
          tag-hash: ${{ steps.envs.outputs.tag-hash }}
          tag-latest: ${{ steps.envs.outputs.tag-latest }}
          build-arg: |-
            --build-arg APP="${{ steps.envs.outputs.app }}" \
            --build-arg ADDITIONAL_ARGUMENTS="${{ steps.envs.outputs.build-options }}"